### ISSUE TITLE
isatty

### ISSUE THREAD

**Issue by ConnyOnny** [RalfJung/lilass#2]
The CLIFrontend's isAvailable-method is a lie. It always returns True, but it actually should return sys.stdout.isatty()
But it can't because then it would be possible for no frontend to be available, which may be okay in some cases (i.e. there are sufficient command line arguments to know what the user wants) but this will still error because of "# load frontend early (for error mssages)".
I suggest we add another frontend, like "CLIFallback" which can only show error strings to stderr but can't let the user choose anything and is always available. This would then be used when neither pyqt nor zenity are available and lilass is run in a non-interactive terminal.

**Comment by RalfJung** [comment]
This is a regression introduced by your #1, but it's also a good catch! I solved this slightly differently, keeping `CLIFrontend` always available but failing in `setup` if there's no TTY. I also made sure we detect a TTY on stdin, which is where we actually need it most, I think.

Please re-open if you think the issue has not actually been fixed.
