### ISSUE TITLE
cli frontend default when called in terminal

### ISSUE THREAD

**Issue by ConnyOnny** [RalfJung/lilass#6]
How about we use the cli frontend by default if we are called from a terminal?

**Comment by RalfJung** [comment]
I don't think that makes sense. I often call lilass from the terminal during development when I want to use the Qt frontend. You can easily add an alias to your shell if you want that behavior locally.

This is also in line with other applications like emacs, that only start on CLI mode if there is no X server around or if you pass specific arguments.

Closing for now. If you have some good arguments for your request, feel free to add them.
